In [10]:
import torch

a = torch.tensor(
    [
        [0,0,1,0],
        [1,0,1,0],
        [0,0,1,1]
    ]
)

a_max, _ = torch.max(a, dim=0)
a_min, _ = torch.min(a, dim=0)

mask_indices = torch.nonzero(a_max != a_min).squeeze()
a_filtered = a[:, mask_indices]
print(a_filtered)
print(a_max)
print(a_min)
# print(mask)
print(mask_indices)

tensor([[0, 0],
        [1, 0],
        [0, 1]])
tensor([1, 0, 1, 1])
tensor([0, 0, 1, 0])
tensor([0, 3])
